USE PRODUCT;

DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(
	NUM INT PRIMARY KEY AUTO_INCREMENT,
    DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP EVENT IF EXISTS INTSERT_EVENT;
CREATE EVENT INTSERT_EVENT
ON SCHEDULE EVERY 30 SECOND
STARTS '2024-07-25 12:35:00'
DO
	INSERT INTO TEST() VALUES();
    
# 이벤트 스케쥴러 확인 
SELECT * FROM information_schema.EVENTS;

# 이벤트 스케쥴러 상태 확인
SHOW VARIABLES LIKE 'event%';

# 이벤트 스케쥴러 상태 변경
SET GLOBAL ENVET_SCHEDULER = ON; # ON OR OFF
